;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	hungry-delete-backward
	org-beginning-of-line
	org-end-of-line
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	helm-M-x
	mac-mwheel-scroll
	mouse-drag-mode-line
	mouse-select-window
	org-shiftdown
	org-shiftright
	org-shiftup
	yas-visit-snippet-file
	))
