;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        end-of-visual-line
        hungry-delete-backward
        indent-for-tab-command
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        sgml-slash
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        dap-mode-mouse-set-clear-breakpoint
        dap-tooltip-mouse-motion
        duplicate-current-line-or-region
        helm-M-x
        helm-confirm-and-exit-minibuffer
        mac-mwheel-scroll
        mouse-drag-mode-line
        mouse-select-window
        mouse-set-region
        org-shiftdown
        org-shiftright
        org-shiftup
        query-replace
        save-region-or-current-line
        swiper-isearch-thing-at-point
        yaml-electric-dash-and-dot
        yas-visit-snippet-file
        ))
